<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title><%= htmlWebpackPlugin.options.title %></title>
    <meta name="description" content="<%= htmlWebpackPlugin.options.description %>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="theme-color" content="<%= htmlWebpackPlugin.options.color %>">
</head>
<body>
<!--[if IE]>
    <p>You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
<![endif]-->
    <h1>Webpack Boilerplate</h1>
    <h2>Use for HTML, SASS, and ES6 Projects</h2>
</body>
</html>